### PR TITLE
feat: 拉伸扩展 Stretch Ext (Ported From TurboWarp) (licenses added)

### PR DESCRIPTION
**Pull request by Arkos123**
- There have been similar blocks in Arkos' Extension, which are buggy however.   
- So I port the TurboWarp version to Gandi. Similar blocks in Arkos' Extension will be removed in the future. 
image
image

### CODE REVIEW

**Comment by fath11** [comment]
Can you confirm this will work with Gandi's interpolation?

**Comment by Arkos123** [comment]
> Can you confirm this will work with Gandi's interpolation mode?

it can work normally in interpolatretching mode, although interpolation doesn't act on the stretching

**Comment by WP-Studio01** [comment]
very good

**Comment by sylarhcn** [comment]
> @sylarhcn are we allowed to move all Turbowarp ported extensions into the Turbowarp folder made in this PR? Each TW creator will receive a dedicated folder for easier management when the original creator decides to take over the ported extension.

yes，I think this is great idea.

**Comment by sylarhcn** [comment]
OH, it already in that folder.

**Pull request merged**
