### PR TITLE
Create Forbidden.js

### PR DESCRIPTION
**Pull request by DilemmaGX**
Filter sensitive words

### CODE REVIEW

**Comment by fath11** [comment]
image
very funny

**Comment by fath11** [comment]
image
Can I make a new list for the International version? This extension is helpful for creators to block certain words.

Also, can we put the list of blocked words in a JSON file? Then we can use `import from` so the actual extension code is not too long.

**Comment by DilemmaGX** [comment]
> image Can I make a new list for the International version? This extension is helpful for creators to block certain words.

Well I'm adding block words based on JSON array. But you can still provide different lists.

**Comment by fath11** [comment]
[InternationalDefault.json](https://github.com/Gandi-IDE/custom-extension/files/14154718/InternationalDefault.json)
Contains words that should be blocked internationally. Based off https://www.freewebheaders.com/youtube-blacklist-words-free-and-youtube-comment-moderation/ and filtered to remove words that consider acceptable by 13+.

Words added to list:
`Gyatt`

**Comment by fath11** [comment]
The list above consider your extension not case sensitive.

**Pull request closed without merging**
