### PR TITLE
feat: 添加飞书扩展

### PR DESCRIPTION
**Pull request by yuen619**
2023-11-27: ⚠To operate it normally, you must bring your own Cast and Axios, otherwise it cannot be loaded properly.

### CODE REVIEW

**Comment by 1886r** [comment]
Oh!No!
You and I have the same design!

**Comment by kukemc** [comment]
> > Oh!No! You and I have the same design!
> 
> This is not correct. In fact, we started preparing as early as April 13th. Are you kidding?

true

**Comment by yuen619** [comment]
> > > Oh!No! You and I have the same design!
> > 
> > 
> > This is not correct. In fact, we started preparing as early as April 13th. Are you kidding?
> 
> true

Of course, thanks to kuke

**Comment by kukemc** [comment]
Has passed the audit.

**Comment by yuen619** [comment]
Has passed the audit.

**Comment by kukemc** [comment]
sylarhcn: Has passed the audit. 
image

**Comment by kukemc** [comment]
@little-starts

**Comment by yuen619** [comment]
@little-starts

**Comment by 1886r** [comment]
> 2023-11-27：⚠要正常运行，必须自备 Cast 和 Axios，否则无法正常加载。
这 一般人会为了用拓展而下nodejs，再下这两个库吗 @YUEN

**Comment by kukemc** [comment]
> > 2023-11-27：⚠要正常运行，必须自备 Cast 和 Axios，否则无法正常加载。
> > 这 一般人会为了用拓展而下nodejs，再下这两个库吗 @Yuen

天才 出院

**Comment by MoreBugOfDog** [comment]
> > > 2023-11-27：⚠要正常运行，必须自备 Cast 和 Axios，否则无法正常加载。
> > > 这 一般人会为了用拓展而下nodejs，再下这两个库吗 @Yuen
> 
> 天才 出院

那时懵懂无知（）

**Pull request merged**
