### PR TITLE
Create gamepad extension

### PR DESCRIPTION
**Pull request by fath11**
A port from Gamepad expanded extension from Turbowarp made by https://github.com/GarboMuffin, https://github.com/DNin01 and https://github.com/Meehdrescher.

### CODE REVIEW

**Comment by DilemmaGX** [comment]
Hello fath11
I was wondering if you can checkout this (If you have any access problem, email me or comment here): https://gandi.rth1.app/Scripts/Gamepad.js
This is the source js file of Gamepad.js I made, with checked `zh-cn` translations and an extra block which can be used in my new ext `Three`.

**Comment by fath11** [comment]
> Hello fath11 I was wondering if you can checkout this (If you have any access problem, email me or comment here): https://gandi.rth1.app/Scripts/Gamepad.js This is the source js file of Gamepad.js I made, with checked `zh-cn` translations and an extra block which can be used in my new ext `Three`.

so you added the vortex block?
image

**Comment by DilemmaGX** [comment]
> > Hello fath11 I was wondering if you can checkout this (If you have any access problem, email me or comment here): https://gandi.rth1.app/Scripts/Gamepad.js This is the source js file of Gamepad.js I made, with checked `zh-cn` translations and an extra block which can be used in my new ext `Three`.
> 
> so you added the vortex block? image

Yes, it's still in dev (not stable). I can't test this block (stuck in school, can't use my gamepad bruh). The l10n is checked, so maybe you can use the zh-cn part.

**Comment by fath11** [comment]
@DilemmaGX i added the checked translation. Can you test it with this https://[fath11.github.io/test/test33.js](https://fath11.github.io/test/test33.js)

**Comment by DilemmaGX** [comment]
> @DilemmaGX i added the checked translation. Can you test it with this https://fath11.github.io/test/test33.js

I guess it's ok.
Well, the extension's name is having some issue. I think you can fix this part (at the end of the script):
image

**Comment by fath11** [comment]
> I guess it's ok. Well, the extension's name is having some issue. I think you can fix this part (at the end of the script): image

oh yeah, i fixed this in my test version but forgot to push it here

**Comment by fath11** [comment]
closed in favour for #209

**Pull request closed without merging**
