### PR TITLE
MarkDown V1.0

### PR DESCRIPTION
**Pull request by little-starts**
feat(code):markdown拓展，支持显示markdown内容

### CODE REVIEW

**Comment by fath11** [comment]
isnt this just BBCode?

**Comment by MoreBugOfDog** [comment]
wow！

**Comment by little-starts** [comment]
> isnt this just BBCode? well its simpler so i guess its good for people that cant do BBCode

BBcode will able to ues [markdown] tag in next update,i guess.

**Comment by xiaochen004hao** [comment]
> wow！

被抢先了吧

**Pull request merged**
