### PR TITLE
ScratchHub extension

### PR DESCRIPTION
**Pull request by fath11**
Fetch users and project data using ScratchDB API. 
https://scratchdb.lefty.one/v3/docs/

Planned features:
- the ability to add iframe embed of Scratch projects using Turbowarp/Cocrea into Gandi projects
- ability to fetch forum data

### CODE REVIEW

**Comment by qxsck** [comment]
the API is use scratch.mit.edu?

**Comment by fath11** [comment]
> the API is use scratch.mit.edu?

It is used by ScratchStats. The about page is here https://scratchdb.lefty.one/

**Comment by qxsck** [comment]
> > the API is use scratch.mit.edu?
> 
> It is used by ScratchStats. The about page is herehttps://scratchdb.lefty.one/

emm,my mean is the api'data is from scratch.mit.edu?

**Comment by fath11** [comment]
> > > the API is use scratch.mit.edu?
> > 
> > 
> > It is used by ScratchStats. The about page is herehttps://scratchdb.lefty.one/
> 
> emm,my mean is the api'data is from scratch.mit.edu?

sorry my bad, yes the data is from scratch.mit.edu

**Comment by qxsck** [comment]
> > > > the API is use scratch.mit.edu?
> > > 
> > > 
> > > It is used by ScratchStats. The about page is herehttps://scratchdb.lefty.one/
> > 
> > 
> > emm,my mean is the api'data is from scratch.mit.edu?
> 
> sorry my bad, yes the data is from scratch.mit.edu

thanks,but I think mit'data not necessary in gandi

**Comment by DilemmaGX** [comment]
Well, scratch.mit.edu was banned in China, so there should be some problems accessing it (need vpn).

**Pull request merged**
