### PR TITLE
新的扩展

### PR DESCRIPTION
**Pull request by Scratcher-CCW**
我提交了新的扩展，文件被存储在extensions\Scratcher中，请HCN审核，谢谢

### CODE REVIEW

**Comment by fath11** [comment]
all the functionalities of this PR are already present in other extensions.
also, please dont submit utilities extension as we dont need them anymore. only extensions that offers specific features should be submitted

**Comment by Scratcher-CCW** [comment]
> 此 PR 的所有功能都已存在于其他扩展中。另外，请不要提交实用程序扩展，因为我们不再需要它们了。仅应提交提供特定功能的扩展
> 
> 在我忘记之前，扩展的横幅和徽标的数据 URI 占用了太多空间，建议将资产放在单独的文件中，合并后 HCN 会将它们放在一起

Okay,thank you.

**Comment by Scratcher-CCW** [comment]
> all the functionalities of this PR are already present in other extensions. also, please dont submit utilities extension as we dont need them anymore. only extensions that offers specific features should be submitted
> 
> and before i forget, the Data URI of the extension's banner and logo are taking too much space, it is recommended to put the assets in a separate file and HCN will put them together after merging

Can you give a few examples of specific features?

**Comment by fath11** [comment]
> Can you give a few examples of specific features?

you will know what people need if you use the thing you are contributing to.

if you know WebGL then we really need a better way to render custom shaders such as applying shaders to a specific sprite which is what i am working on right now. Or a better extension to replace the official Canvas extension which will have features such as textured shapes. 

if you want a simpler extension to work on, an extension that can generate Perlin noise or other noise algorithm will be really appreciated. Or a better collision system to replace Gandi IDE's `touching()` block. basically any feature that cannot be achieved right now with the current extension collection

**Pull request closed without merging**
