### PR TITLE
Update Comment blocks

### PR DESCRIPTION
**Pull request by fath11**
Changed the banner to match the block's colour palate
I moved Comment blocks to a new Turbowarp folder.

Also, @sylarhcn, can you remove my name from the credits section of Comment blocks and Big Int? I hope my name won't be displayed in any Turbowarp ported extensions I committed.

### CODE REVIEW

**Comment by sylarhcn** [comment]
you dont want show your name? why?

**Comment by fath11** [comment]
> you dont want show your name? why?

just ones that i do not make any significant changes to. porting those extensions doesn't take much effort so i rather not have it under my name

**Comment by fath11** [comment]
also can i know why you guys choose LGPLV2.1?

**Comment by sylarhcn** [comment]
> also can i know why you guys choose LGPL v2.1?

I think there's no particular, chose it by default maybe. :D

**Pull request merged**
