### PR TITLE
Update var-and-list.js

### PR DESCRIPTION
**Pull request by qxsck**
fix i10n

### CODE REVIEW

**Comment by qxsck** [comment]
@fath11 fix now

**Comment by fath11** [comment]
you should consider #170

**Comment by qxsck** [comment]
> you should consider #170

thanks

**Comment by qxsck** [comment]
new block:set list to value times
image
新的积木，设置列表为指定数量个值
image

**Comment by qxsck** [comment]
three new blocks:

swap variables or lists

associate lists, contrary to the function of "mapObject"

**Pull request merged**
