### PR TITLE
BetterQuake

### PR DESCRIPTION
**Pull request by fath11**
Screenshot 2024-09-19 212834

### CODE REVIEW

**Comment by fath11** [comment]
Please visit https://github.com/QuakeStudio/BetterQuake. The files provided here are NOT meant to be edited or viewed, thank you.

**Comment by fath11** [comment]
Chinese translation needs reviewing https://github.com/QuakeStudio/BetterQuake/blob/main/src/l10n.json

**Comment by qxsck** [comment]
cool

**Comment by sylarhcn** [comment]
seems a great extenison.
I've been busy with other projects recently. I'll find some time during the national holiday to merge.

**Comment by fath11** [comment]
## Normal map lighting with Better Quake

Screenshot 2024-09-29 185606
Screenshot 2024-09-29 191052
Screenshot 2024-09-29 193422

**Comment by fath11** [comment]
refactor by FurryR

**Comment by xiaochen004hao** [comment]
hcn不是说国庆就能上线吗？（10.1-10.7）

**Comment by HanHanDeYaYa** [comment]
When is it expected to be launched?

**Comment by fath11** [comment]
@sylarhcn the banner for the extension is included in assets/banner.png

**Pull request merged**
