### PR TITLE
添加扩展：Scratcherの屏幕Pro（Add Extension: Scratcher's Screen Pro）

### PR DESCRIPTION
**Pull request by Scratcher-CCW**
扩展名称：Scratcherの屏幕Pro
Extension name: Scratcher's Screen Pro
扩展作用：获取屏幕和浏览器的分辨率
Extension: Get the resolution of the screen and browser

### CODE REVIEW

**Comment by qxsck** [comment]
docs使用方法不对，或者说这种方法并不适合

**Comment by Scratcher-CCW** [comment]
> docs使用方法不对，或者说这种方法并不适合

怎么适合，白猫的用法就是这样的

**Comment by qxsck** [comment]
> > docs使用方法不对，或者说这种方法并不适合
> 
> 怎么适合，白猫的用法就是这样的

docsURL

**Comment by Scratcher-CCW** [comment]
> > > docs使用方法不对，或者说这种方法并不适合
> > 
> > 
> > 怎么适合，白猫的用法就是这样的
> 
> 文档网址

网址怎么了，是还没完善吗

**Comment by qxsck** [comment]
> > > > docs使用方法不对，或者说这种方法并不适合
> > > 
> > > 
> > > 怎么适合，白猫的用法就是这样的
> > 
> > 
> > 文档网址
> 
> 网址怎么了，是还没完善吗

？

**Comment by qxsck** [comment]
> > > > docs使用方法不对，或者说这种方法并不适合
> > > 
> > > 
> > > 怎么适合，白猫的用法就是这样的
> > 
> > 
> > 文档网址
> 
> 网址怎么了，是还没完善吗

https://github.com/Gandi-IDE/custom-extension/blob/a6ab656ba5ad93bb6cf3552bcd13174e0b9b457e/extensions/Arkos/advancedControls.js#L289
你可以看这个

**Comment by fath11** [comment]
all these blocks doesnt accept any arguments, they can be merged into one block and be putted inside More Sensing

**Comment by Scratcher-CCW** [comment]
> > > > > docs使用方法不对，或者说这种方法并不适合
> > > > 
> > > > 
> > > > 怎么适合，白猫的用法就是这样的
> > > 
> > > 
> > > 文档网址
> > 
> > 
> > 网址怎么了，是还没完善吗
> 
> https://github.com/Gandi-IDE/custom-extension/blob/a6ab656ba5ad93bb6cf3552bcd13174e0b9b457e/extensions/Arkos/advancedControls.js#L289
> 
> 
> 你可以看这个

要放在formatmessage里？

**Comment by qxsck** [comment]
> > > > > > docs使用方法不对，或者说这种方法并不适合
> > > > > 
> > > > > 
> > > > > 怎么适合，白猫的用法就是这样的
> > > > 
> > > > 
> > > > 文档网址
> > > 
> > > 
> > > 网址怎么了，是还没完善吗
> > 
> > 
> > https://github.com/Gandi-IDE/custom-extension/blob/a6ab656ba5ad93bb6cf3552bcd13174e0b9b457e/extensions/Arkos/advancedControls.js#L289
> > 
> > 你可以看这个
> 
> 要放在formatmessage里？

自己看

**Comment by Scratcher-CCW** [comment]
> all these blocks doesnt accept any arguments, they can be merged into one block and be putted inside More Sensing

OK,I'll try

**Comment by Scratcher-CCW** [comment]
> all these blocks doesnt accept any arguments, they can be merged into one block and be putted inside More Sensing

I couldn't read his code at all, his code was so complex that the custom extension wouldn't load at all when I wrote it

**Review by MoreBugOfDog — CHANGES_REQUESTED** [review]
Hello developers!
The [Get Resolution][Modify Resolution] function is already covered in witcat@CCW's extension 😊😊😊😊
Suggested to give More Sensing a PR instead of a new extension.
This kind of extension is recommended to go the kit route in the [Extension Lab Square].

**Comment by Scratcher-CCW** [comment]
> 获取分辨率

Which extension includes the ability to get the resolution?

**Comment by Scratcher-CCW** [comment]
> Hello developers! The [Get Resolution][Modify Resolution] function is already covered in witcat@CCW's extension 😊😊😊😊 Suggested to give More Sensing a PR instead of a new extension. This kind of extension is recommended to go the kit route in the [Extension Lab Square].

Which extension includes the ability to get the resolution?

**Pull request closed without merging**
