### PR TITLE
feat：Three 三扩展新增积木

### PR DESCRIPTION
**Pull request by Arkos123**
feat: 新积木：求单位向量；根据方向创建向量
feat: 向量+-*/允许形如[1,2,3]*2的单个值写法
feat: 获取3D向量信息，增加xy/yz/xz选项
image
image

### CODE REVIEW

**Comment by xiaochen004hao** [comment]
学glsl？

**Comment by Nightre** [comment]
arkos大好人

**Comment by qxsck** [comment]
arkos大好人

**Comment by fath11** [comment]
someone has been begging me for 1 week straight for this PR to be merged 😭😭

**Comment by xiaochen004hao** [comment]
> someone has been begging me for 1 week straight for this PR to be merged 😭😭

who?

**Pull request merged**
