### PR TITLE
修复simple_reporter.js的问题，提交 简单运动 拓展  0301更新

### PR DESCRIPTION
**Pull request by MoreBugOfDog**
我已经修复了有问题的拓展，可以合并，具体内容麻烦移步下面的评论。

————————————————————————历史内容——————————————————————————

现在，bilioicik已经更新了他的拓展simple_reporter修复了已知问题，同时，添加了简单运动拓展。
请再次审核，谢谢
对于numpro.js，请不要把他添加到gandi仓库，因为他的设置页还有问题，因为一些原因不能到新分支去测试。
此外，我有一个小问题：
如果此次拓展提交成功，是否可以使用README中CCW approved extension的方法，直接推送到此仓库中，进行测试？

### CODE REVIEW

**Comment by fath11** [comment]
why no √-1 /j

**Comment by fath11** [comment]
A lot of the blocks in this extension already exist in other extensions.

The Base category of this extension can already be done with Biter, and the String category can be done with String process extension. And the Boolean category can be done with my currently pending #141 . It will be better if a specific extension only does a particular thing instead of multiple things that can be split.

You would be better off expanding upon the Graph category, and now, without any extra blocks, there can be even more possibilities for it. This is just my opinion; you can do whatever you want.

**Comment by fath11** [comment]
Also you just need to replace 
`Scratch.extensions.register(new Operation());
})(Scratch);` 

in the code with

```js
window.tempExt = {
  Extension: Operation /*extension class*/,
  info: {
    name: 'hcn.extensionName',
    description: 'hcn.description',
    extensionId: 'OPERATION',
    // iconURL: cover,
    // insetIconURL: icon,
    featured: true,
    disabled: false,
    collaborator: 'name',
    collaboratorList: [
        {
            collaborator: 'name',
            collaboratorURL: 'url'
        },
    ]
  },
  l10n: {
    'zh-cn': {
      'hcn.extensionName': 'hcn 的测试',
      'hcn.description': 'hcn 的测试',
    },
    en: {
      'hcn.extensionName': 'hcn test',
      'hcn.description': 'hcn test',
    },
  },
}
```

change the snipped accordingly to make it compatible with gandi

**Comment by sylarhcn** [comment]
> Also you just need to replace `Scratch.extensions.register(new Operation()); })(Scratch);`
> 
> in the code with
> 
> ```js
> window.tempExt = {
>   Extension: Operation /*extension class*/,
>   info: {
>     name: 'hcn.extensionName',
>     description: 'hcn.description',
>     extensionId: 'OPERATION',
>     // iconURL: cover,
>     // insetIconURL: icon,
>     featured: true,
>     disabled: false,
>     collaborator: 'name',
>     collaboratorList: [
>         {
>             collaborator: 'name',
>             collaboratorURL: 'url'
>         },
>     ]
>   },
>   l10n: {
>     'zh-cn': {
>       'hcn.extensionName': 'hcn 的测试',
>       'hcn.description': 'hcn 的测试',
>     },
>     en: {
>       'hcn.extensionName': 'hcn test',
>       'hcn.description': 'hcn test',
>     },
>   },
> }
> ```
> 
> change the snipped accordingly to make it compatible with gandi


Gandi now support this extension register function
`Scratch.extensions.register(new Operation())`

and this info is also useful，it will used in ext menu when published
```
info: {
    name: 'hcn.extensionName',
    description: 'hcn.description',
    extensionId: 'OPERATION',
    // iconURL: cover,
    // insetIconURL: icon,
    featured: true,
    disabled: false,
    collaborator: 'name',
    collaboratorList: [
        {
            collaborator: 'name',
            collaboratorURL: 'url'
        },
    ]
  },
  l10n: {
    'zh-cn': {
      'hcn.extensionName': 'hcn 的测试',
      'hcn.description': 'hcn 的测试',
    },
    en: {
      'hcn.extensionName': 'hcn test',
      'hcn.description': 'hcn test',
    },
  },
```

**Comment by sylarhcn** [comment]
acorrding review by fath11
this extension seems has same block as exsiting ext
I will pending it now.
it still have chance to publish, we are refactor the Extenison System, it will open to every ext developer to publish their blocks directly in gandi.

**Comment by fath11** [comment]
The colour palate for the popup should match either Gandi's palate or the extension's palate.

image

It might be easier to use Gandi IDE's colour palate since you can feed in the CSS variables that Gandi already has, which means the popup will also support dark and light themes.

image

**Comment by 1886r** [comment]
> 快闪店的颜色口感应与 Gandi 的口感或扩展的口感相匹配。
> 
> image
> 
> 使用 Gandi IDE 的 Color Palate 可能会更容易，因为您可以输入 Gandi 已有的 CSS 变量，这意味着弹出窗口也将支持深色和浅色主题。
> 
> image

Hello, fath11.
The setup interface in this extension mimics the interface in scratch's "micro:bit" extension.
Can we expand "operation pro" to gandi IDE first? UI issues will be submitted with the next expansion update.

**Comment by fath11** [comment]
k

**Comment by 1886r** [comment]
> 快闪店的颜色口感应与 Gandi 的口感或扩展的口感相匹配。
> 
> image
> 
> 使用 Gandi IDE 的 Color Palate 可能会更容易，因为您可以输入 Gandi 已有的 CSS 变量，这意味着弹出窗口也将支持深色和浅色主题。
> 
> image

Hello, fath11.
We have noticed that the position of the text in the Settings window is offset on your computer. I was wondering, what browser are you using? Is there scaling?

**Comment by fath11** [comment]
Microsoft edge

**Comment by sylarhcn** [comment]
it's seems you inject a UI to Gandi，what is it？
and it‘s still have bugs with layout.
Color theme is not Gandi style alsoe.

**Comment by 1886r** [comment]
我帮助bilioicik提交拓展。
已经经过测试了
不设置icon。
至于numpro，弹窗适配问题正在解决
无需审核numpro，只需审核simple reporter即可
非常感谢

**Comment by qxsck** [comment]
> 我帮助bilioicik提交拓展。 已经经过测试了 不设置icon。 至于numpro，弹窗适配问题正在解决 无需审核numpro，只需审核simple reporter即可 非常感谢

这应该新开一个pr而不是在老的pr添加

**Comment by fath11** [comment]
image
i doesnt like how these uses empty items, there is no need to do that

**Comment by fath11** [comment]
No offence, but this simple reporter extension will be a palate bloat. It doesn't provide any value to Gandi. I know the creator is still learning, and this is his first time, but I want to make sure Gandi IDE's extension gallery is not filled with bloats _(a great time to remind about being able to share projects with custom extensions)_ .

**Comment by 1886r** [comment]
> 没有冒犯，但这个简单的记者扩展将是一种味觉膨胀。它不会给 Gandi 提供任何价值。我知道创建者还在学习，这是他第一次学习，但我想确保 Gandi IDE 的扩展库不会充满臃肿_（这是提醒能够使用自定义扩展分享项目的好时机）。_

Thanks for your reply.
I have received your suggestion, and I will relay it to bilioicik.

**Comment by 1886r** [comment]
> > 我帮助bilioicik提交拓展。已经经过测试了 不设置icon。至于numpro，弹窗适配问题正在解决 无需审核numpro，只需审核simple reporter即可 非常感谢
> 
> 这应该新开一个pr而不是在老的pr添加

I received it.

**Comment by 1886r** [comment]
@fath11 @sylarhcn 可以加快拓展审核速度嘛（）我和bilioicik要等不及了（）（）

**Comment by 1886r** [comment]
@fath11 @sylarhcn 可以加快拓展审核速度嘛（）我和bilioicik要等不及了（）（）

**Review by sylarhcn — CHANGES_REQUESTED** [review]
1. 所有的扩展 id 最好都加上前缀，避免被轻松的重复。
2. 这个 pr 中有多个扩展，但是根据你的描述，有些扩展还没有写完或者有bug。我没发部分合并一个 pr
3. 请没个 pr 只包含一个扩展，这样才能方便爱好者们 review 测试和讨论

**Comment by 1886r** [comment]
> 1. 所有的扩展 id 最好都加上前缀，避免被轻松的重复。
> 2. 这个 pr 中有多个扩展，但是根据你的描述，有些扩展还没有写完或者有bug。我没发部分合并一个 pr
> 3. 请没个 pr 只包含一个扩展，这样才能方便爱好者们 review 测试和讨论

HCN，你好
非常抱歉，我无法提交多个pr（有一个pr后就没有创建pr的按钮了）
有问题的拓展已经修复完毕，保证不会造成问题
对于对拓展爱好者们带来的不便，我深感抱歉，有问题麻烦 @1886r 解决，谢谢
您可以再次审核，然后合并他

**Comment by fath11** [comment]
> I'm sorry, I can't submit multiple PRs (there is no button to create PRs after one PR)
Could you make a new branch in your fork of this repo? You can make multiple PRs if they are in a different branch.

> If the extension is successfully submitted, can I use the CCW approved extension method in the README to push it directly to this repository for testing?
The README is outdated, and as Sylarhcn said, he won't merge partially finished PRs. Figure out how to test your extensions yourself. And no, if your extension is merged, you won't be given permission to merge other PRs.

**Comment by fath11** [comment]
Here is my recommendations for Simple Motion
image
image

For the turn reporter, it will be more useful for them to have an input field like the normal turn block in Scratch. Making a similar block but for point towards will also be useful

image
??? - idk what that block does.

----------------------------------------------------------------------------

 also i recommend adding these blocks
image
```js
//taken from https://extensions.turbowarp.org/NexusKitten/moremotion.js, there is no need to add all the other blocks
//in the extension, this specific block is all that is needed
steptowards(args, util) {
      const x = Scratch.Cast.toNumber(args.X);
      const y = Scratch.Cast.toNumber(args.Y);
      const steps = Scratch.Cast.toNumber(args.STEPS);
      const val =
        steps / Math.sqrt((x - util.target.x) ** 2 + (y - util.target.y) ** 2);
      if (val >= 1) {
        util.target.setXY(x, y);
      } else {
        util.target.setXY(
          (x - util.target.x) * val + util.target.x,
          (y - util.target.y) * val + util.target.y
        );
      }
    }
```
image
*doesnt have the code, you gonna have to figure out how to code it yourself*

image
*the option to choose which sprite to glide is not needed, just make the block glide the sprite it is on*

```js
//taken from https://sharkpools-extensions.vercel.app/, all the other blocks in the extension are not necessary
betterGlide(args, util, loop) {
      const target = args.NAME === "_myself_" ? util.target : runtime.getSpriteTargetByName(args.NAME);
      if (!util.stackFrame.startTime) {
        util.stackFrame.startTime = new Date().getTime();
        util.stackFrame.duration = Scratch.Cast.toNumber(args.SECS);
        util.stackFrame.startX = target.x;
        util.stackFrame.startY = target.y;
        util.stackFrame.endX = Scratch.Cast.toNumber(args.X);
        util.stackFrame.endY = Scratch.Cast.toNumber(args.Y);
        if (util.stackFrame.duration <= 0) {
          target.setXY(util.stackFrame.endX, util.stackFrame.endY);
          return;
        }
        if (loop === "on") {
          util.startBranch(1, true);
        } else {
          util.yield();
        }
      } else {
        const currentTime = new Date().getTime();
        const timeElapsed = currentTime - util.stackFrame.startTime;
        if (timeElapsed < util.stackFrame.duration * 1000) {
          const frac = timeElapsed / (util.stackFrame.duration * 1000);
          const dx = frac * (util.stackFrame.endX - util.stackFrame.startX);
          const dy = frac * (util.stackFrame.endY - util.stackFrame.startY);
          target.setXY(
            util.stackFrame.startX + dx,
            util.stackFrame.startY + dy
          );
          if (loop === "on") {
            util.startBranch(1, true);
          } else {
            util.yield();
          }
        } else {
          target.setXY(util.stackFrame.endX, util.stackFrame.endY);
        }
      }
    }

    whileGlide(args, util) { this.betterGlide(args, util, "on") }
```

**Comment by fath11** [comment]
the EN translation for Simple Motion will also need some rewrite. once you updated the extension i can rewrite them for you.

**Comment by fath11** [comment]
Simple Motion is excellent, but as I stated before, Simple Reporter should **not** be merged. The sheer number of blocks it offers will be confusing to manage and use.

**Comment by fath11** [comment]
Also **all** reporters that return more than one value should be in JSON. 

For example: 
image
should return `[3.91, 921]` instead

**Review by sylarhcn — CHANGES_REQUESTED** [review]
请关闭该 pr，一个个扩展文件的来提交 pr。
你可以使用 git branch 来隔离不同代码分支

**Comment by MoreBugOfDog** [comment]
> 请关闭该 pr，一个个扩展文件的来提交 pr。 你可以使用 git branch 来隔离不同代码分支

哦，很抱歉给您带来的麻烦，谢谢提醒

**Pull request closed without merging**
