### PR TITLE
创建扩展：Scratcherの数学Pro

### PR DESCRIPTION
**Pull request by Scratcher-CCW**
创建扩展：Scratcherの数学Pro
扩展作用：包括但不限于进制转换（例：二进制转十进制）、布尔值、幂运算
扩展存储目录：extensions\Scratcher\MathPro.js

### CODE REVIEW

**Comment by kukemc** [comment]
此扩展的绝大部分功能都已有相同功能的扩展了，请保证扩展绝大多数功能尽量不会和其他扩展冲突

**Comment by Scratcher-CCW** [comment]
> 此扩展的绝大部分功能都已有相同功能的扩展了，请保证扩展绝大多数功能尽量不会和其他扩展冲突

酷可请问我如果做一个获取浏览器和屏幕的宽高的拓展可以过审吗

**Comment by fath11** [comment]
> Cool, can I make an extension to get the width of the browser and the screen to pass the review?

that can but putted inside More Sensing

**Comment by qxsck** [comment]
docs的链接可以参考下仓库里的其他拓展，这个用法并不好

**Comment by Scratcher-CCW** [comment]
> > Cool, can I make an extension to get the width of the browser and the screen to pass the review?
> 
> that can but putted inside More Sensing

Okay,but what more sensing is?

**Comment by DannyDevPro** [comment]
中国人要讲中国话

**Comment by kukemc** [comment]
> 中国人要讲中国话

人家又不是中国人

**Comment by DannyDevPro** [comment]
大意了 让你得逞了

**Comment by Scratcher-CCW** [comment]
> 大意了 让你得逞了

6

**Comment by DannyDevPro** [comment]
要不你把他改成纯算法扩展试试

**Comment by Scratcher-CCW** [comment]
> 要不你把他改成纯算法扩展试试

放弃了━━(￣ー￣*|||━━

**Comment by DannyDevPro** [comment]
> > 要不你把他改成纯算法扩展试试
> 
> 放弃了━━(￣ー￣*|||━━

额

**Comment by fath11** [comment]
> Okay,but what more sensing is?

More Sensing extension by Arkos

**Comment by Scratcher-CCW** [comment]
> > Okay,but what more sensing is?
> 
> More Sensing extension by Arkos

I didn't find it in the extended library.

**Comment by fath11** [comment]
extensions/Arkos/moreSensing.js

**Comment by Scratcher-CCW** [comment]
> 扩展/Arkos/moreSensing.js

His extension is to get the width and height of the stage, but I want to do an extension to get the width and height of the screen

**Comment by fath11** [comment]
> His extension is to get the width and height of the stage, but I want to do an extension to get the width and height of the screen

you can put that in More Sensing extension, there is no need to make a new one.

**Comment by Scratcher-CCW** [comment]
> > His extension is to get the width and height of the stage, but I want to do an extension to get the width and height of the screen
> 
> you can put that in More Sensing extension, there is no need to make a new one.

What if he won't let me change it?

**Comment by fath11** [comment]
this is an open source repository, you are allowed to make changes to anything IF those changes are meaningful

**Comment by Scratcher-CCW** [comment]
> this is an open source repository, you are allowed to make changes to anything IF those changes are meaningful

I don't think it's good, I may not understand his extension, I use the extension template of wit-cat

**Comment by fath11** [comment]
its still not a good idea to make an extension with very few blocks. you should learn how to read other people's code

**Comment by Scratcher-CCW** [comment]
> 用很少的块进行扩展仍然不是一个好主意。你应该学习如何阅读别人的代码

My extension doesn't just contain a few blocks, my extension contains twelve blocks

**Comment by fath11** [comment]
> My extension doesn't just contain a few blocks, my extension contains twelve blocks

i am talking about the screen size and window size block

**Comment by Scratcher-CCW** [comment]
> > My extension doesn't just contain a few blocks, my extension contains twelve blocks
> 
> i am talking about the screen size and window size block

Yeah,I'm talking about the screen size and window size block too

**Pull request closed without merging**
