### PR TITLE
Create fetch.js

### PR DESCRIPTION
**Pull request by yunyun2010**
自己要用

### CODE REVIEW

**Comment by MoreBugOfDog** [comment]
Don't duplicate PR submissions! This extension won't pass muster, so please don't be so unreasonable! This is seriously disrupting the development order! Close the PR immediately!

**Review by MoreBugOfDog — CHANGES_REQUESTED** [review]
Don't duplicate PR submissions! This extension won't pass muster, so please don't be so unreasonable! This is seriously disrupting the development order! Close the PR immediately!

**Comment by kukemc** [comment]
没绷住

**Comment by qxsck** [comment]
so terrible！你应该关闭这些请求

**Comment by yunyun2010** [comment]
奥

**Comment by yunyun2010** [comment]
好吧

**Pull request closed without merging**
